apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sc-host-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sc-host-2
        sc: storage-cluster1
    spec:
      nodeSelector:
        kubernetes.io/hostname: m3cluster-worker2
      containers:
        - name: tenant-1-minio-2
          image: "minio/minio:RELEASE.2019-09-26T19-42-35Z"
          imagePullPolicy: "IfNotPresent"
          args:
            - server
            - "--address"
            - ":9001"
            - http://sc-host-{1...4}:9001/mnt/tdisk{1...4}
          envFrom:
            - configMapRef:
                name: tenant-1-env
          volumeMounts:
            - mountPath: /mnt/tdisk1
              name: tenant-1-pv-1
            - mountPath: /mnt/tdisk2
              name: tenant-1-pv-2
            - mountPath: /mnt/tdisk3
              name: tenant-1-pv-3
            - mountPath: /mnt/tdisk4
              name: tenant-1-pv-4
          ports:
            - containerPort: 9001
              name: http
        - name: tenant-2-minio-2
          image: "minio/minio:RELEASE.2019-09-26T19-42-35Z"
          imagePullPolicy: "IfNotPresent"
          args:
            - server
            - "--address"
            - ":9002"
            - http://sc-host-{1...4}:9002/mnt/tdisk{1...4}
          envFrom:
            - configMapRef:
                name: tenant-2-env
          volumeMounts:
            - mountPath: /mnt/tdisk1
              name: tenant-2-pv-1
            - mountPath: /mnt/tdisk2
              name: tenant-2-pv-2
            - mountPath: /mnt/tdisk3
              name: tenant-2-pv-3
            - mountPath: /mnt/tdisk4
              name: tenant-2-pv-4
          ports:
            - containerPort: 9002
              name: http
      volumes:
        # tenant-1 volumes
        - name: tenant-1-pv-1
          hostPath:
            path: /mnt/disk1/tenant-1
        - name: tenant-1-pv-2
          hostPath:
            path: /mnt/disk2/tenant-1
        - name: tenant-1-pv-3
          hostPath:
            path: /mnt/disk3/tenant-1
        - name: tenant-1-pv-4
          hostPath:
            path: /mnt/disk4/tenant-1
        # tenant-2 volumes
        - name: tenant-2-pv-1
          hostPath:
            path: /mnt/disk1/tenant-2
        - name: tenant-2-pv-2
          hostPath:
            path: /mnt/disk2/tenant-2
        - name: tenant-2-pv-3
          hostPath:
            path: /mnt/disk3/tenant-2
        - name: tenant-2-pv-4
          hostPath:
            path: /mnt/disk4/tenant-2
