---
apiVersion: v1
kind: Service
metadata:
  name: m3-vault
  labels:
    name: m3-vault
spec:
  ports:
    - port: 8200
      name: rest-api
  selector:
    app: m3-vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m3-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m3-vault
  template:
    metadata:
      labels:
        app: m3-vault
    spec:
      containers:
        - name: m3-vault
          image: minio/m3-vault:edge
          imagePullPolicy: "IfNotPresent"
          args:
            - /m3-vault
          env:
            - name: SECRET_SHARES
              value: "5"
            - name: SECRET_THRESHOLD
              value: "3"
          ports:
            - containerPort: 8200
              name: rest-api
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
